# docker-compose.yml
services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: gcm
      POSTGRES_USER: gcm
      POSTGRES_PASSWORD: gcm
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
